name: Run Pytest on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python version

      # Step 3: Set PYTHONPATH to include the current directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # Step 4: Install dependencies and local module
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      # Step 5: Run pytest with coverage
      - name: Run Pytest with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=sleeper_api --cov-report=xml
